name: login_app
description: A Flutter application for login and navigation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0
  flutter_login_template: ^1.0.0
  audioplayers: ^0.20.0  # Add this line to include the audioplayers package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_avatar.jpg
    - assets/images/login.jpg
    - assets/images/gopal.jpg
    - assets/images/adhi.jpg
    - assets/images/Rahul vazha.jpg
    - assets/images/rachana.jpg
    - assets/images/devi.jpg
    - assets/images/poppu.jpg
    - assets/images/shravan.jpg
    - assets/images/page5_background.jpg
    - assets/images/profile_picture.jpg
    - assets/images/gif_image.gif
    - assets/toxica.mp3  # Add this line to include the toxica.mp3 file
