name: login_app
description: A Flutter application for login and navigation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0
  flutter_login_template: ^1.0.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  firebase_auth: ^4.3.0
  firebase_database: ^10.0.16
  firebase_analytics: ^10.1.6
  firebase_performance: ^0.9.0
  firebase_remote_config: ^3.0.15
  firebase_crashlytics: ^3.0.17
  firebase_app_check: ^0.1.1
  firebase_core: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_avatar.jpg
    - assets/images/login.jpg
    - assets/images/gopal.jpg
    - assets/images/adhi.jpg
    - assets/images/Rahul vazha.jpg
    - assets/images/rachana.jpg
    - assets/images/devi.jpg
    - assets/images/poppu.jpg
    - assets/images/shravan.jpg
    - assets/images/page5_background.jpg
    - assets/images/profile_picture.jpg
    - assets/images/gif_image.gif
